In [53]:
import numpy as np

p = np.array([[1,2,3,8],[4,5,6,6],[1,2,3,8],[4,5,6,6]])
# print(p.shape)
# p_new_shape = np.array([p.shape[0]/2,p.shape[1]/2],dtype=np.int16)
# print(p_new_shape)
# # i = np.resize(p,p_new_shape)
# i = p[::2,::2]
# print(i)

# i = np.zeros(4)
# for n in range(4):
#     i[n] = n
#     #img = gp[n]

# i = np.zeros(2*p.shape)
# i[::2,::2] = p
# #for n,m in range(p.shape):
# q = np.array([[100,99,88,77],[66,55,44,33],[22,11,98,97],[96,95,94,93]])
# p=np.insert(p[0,:],1,q[0,0])
# p=np.insert(p[0,:],3,q[0,1])
# p=np.insert(p[1],0,q[1,0])
# p=np.insert(p[1],2,q[1,1])
# print(p)
# rows = 2*p.shape[0]
# columns = 2*p.shape[1]

# q = np.zeros(2*p.shape[0])
# # print(len(q))
# q=p[::2,::2]
# print(p)
# print(q)
q=2*p
z=np.multiply(2,p)
print(q)
z

[[ 2  4  6 16]
 [ 8 10 12 12]
 [ 2  4  6 16]
 [ 8 10 12 12]]


array([[ 2,  4,  6, 16],
       [ 8, 10, 12, 12],
       [ 2,  4,  6, 16],
       [ 8, 10, 12, 12]])